version: "3"

services:
  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"
    volumes:
      - ~/docker_volumes/moyu/mongo:/data/db
    networks:
      - isolated

  moyu:
    image: moyu-server:latest
    restart: always
    working_dir: /opt/moyu-server
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "7004:7004"
    networks:
      - isolated

networks:
  isolated:
    name: isolated
